kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "geth-public.fullname" . }}
  annotations:
    {{- if .Values.persistence.resourcePolicyKeep }}
    "helm.sh/resource-policy": keep
    {{- end }}
  labels:
    app: {{ template "geth-public.name" . }}
    chart: {{ template "geth-public.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: node
    org: {{ .Values.organization.id }}
    network: {{ .Values.network.id }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: ""
