image:
  repository: "dysnix/pv-provisioner"
  tag: "latest"
  pullPolicy: Always

rbac:
  serviceAccount: "pv-provisioner"
  clusterRole: "pv-provisioner"
  clusterRoleBinding: "pv-provisioner"

cloud: "gcp"

secret:
  K8S_PERSISTENT_VOLUME_RECLAIM_POLICY: "Delete"
  K8S_CLUSTER_NAME: ""
  GCP_PROJECT: ""
  GCP_ZONE: "asia-southeast1-c"
  GCP_SNAPSHOT_LABEL: "snapshot"
  GCP_DISK_TYPE_URL: "projects/helix-dev-pancake/zones/asia-southeast1-c/diskTypes/pd-ssd"
  GOOGLE_APPLICATION_CREDENTIALS: "/usr/local/etc/gcp-cred.json"