image:
  repository: "arilot/pv-provisioner"
  tag: "latest"
  pullPolicy: Always

rbac:
  serviceAccount: "pv-provisioner"
  clusterRole: "pv-provisioner"
  clusterRoleBinding: "pv-provisioner"

cloud: "gcp"

secret:
  K8S_PERSISTENT_VOLUME_RECLAIM_POLICY: "Delete"
  K8S_CLUSTER_NAME: "demo-pv-provisioner"
  GCP_PROJECT: "graceful-trees-256708"
  GCP_ZONE: "europe-north1-a"
  GCP_SNAPSHOT_LABEL: "snapshot"
  GOOGLE_APPLICATION_CREDENTIALS: "/usr/local/etc/gcp-cred.json"