{{ if eq .Values.cloud "gcp" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "pv-provisioner.fullname" . }}-gcp-cred
  labels:
    app: {{ template "pv-provisioner.name" . }}
    chart: {{ template "pv-provisioner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  gcp-cred.json: |-
    {{ .Files.Get "gcp-cred.json" | b64enc }}

{{ end }}