apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "pv-provisioner.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "pv-provisioner.name" . }}
    chart: {{ template "pv-provisioner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  K8S_PERSISTENT_VOLUME_RECLAIM_POLICY: {{ .Values.secret.K8S_PERSISTENT_VOLUME_RECLAIM_POLICY | b64enc | quote }}
  {{ if eq .Values.cloud "gcp" }}
  GCP_PROJECT: {{ .Values.secret.GCP_PROJECT | b64enc | quote }}
  GCP_ZONES: {{ .Values.secret.GCP_ZONES | b64enc | quote }}
  GCP_SNAPSHOT_LABEL: {{ .Values.secret.GCP_SNAPSHOT_LABEL | b64enc | quote }}
  {{ if .Values.secret.GOOGLE_APPLICATION_CREDENTIALS }}
  GOOGLE_APPLICATION_CREDENTIALS: {{ .Values.secret.GOOGLE_APPLICATION_CREDENTIALS | b64enc | quote }}
  {{ end }}
  GCP_DISK_TYPE: {{ .Values.secret.GCP_DISK_TYPE | b64enc | quote }}
  {{ end }}
  {{ if eq .Values.cloud "aws" }}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.AWS_ACCESS_KEY_ID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.AWS_SECRET_ACCESS_KEY | b64enc | quote }}
  AWS_REGION: {{ .Values.secret.AWS_REGION | b64enc | quote }}
  AWS_ZONE: {{ .Values.secret.AWS_ZONE | b64enc | quote }}
  AWS_VOLUME_TYPE: {{ .Values.secret.AWS_VOLUME_TYPE | b64enc | quote }}
  AWS_SNAPSHOT_LABEL: {{ .Values.secret.AWS_SNAPSHOT_LABEL | b64enc | quote }}
  K8S_CLUSTER_NAME: {{ .Values.secret.K8S_CLUSTER_NAME | b64enc | quote }}
  {{ end }}

