apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: {{ .Values.rbac.serviceAccount | quote }}
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- range $key, $value := .Values.rbac.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
    app: {{ template "pv-provisioner.name" . }}
    chart: {{ template "pv-provisioner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}