apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: {{ .Values.rbac.serviceAccount | quote }}
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
    app: {{ template "pv-provisioner.name" . }}
    chart: {{ template "pv-provisioner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}